<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // [
            //     'employee_name'     => 'Suhanda',
            //     'gender'            => 'Laki-Laki',
            //     'marital_status'    => 'Kawin',
            //     'num_children'      => 0,
            //     'image'             => 'default.png',
            //     'education'         => 'SLTA',
            //     'employee_address'  => 'Jl. Taruna Jaya, RT.005/RW.013, Kel.Cibubur, Kec.Ciracas',
            //     'email'             => 'suhanda11@gmail.com',
            //     'telephone'         => '089667215960',
            //     'birth_place'       => 'Jakarta',
            //     'birth_date'        => '1969-12-31',
            //     'hire_date'         => '2023-01-02',
            //     'contraceptive_use' => 'Tidak',
            //     'rptra_name'        => 'Cibubur Berseri',
            //     'rptra_address'     => 'Jl. H. Abdul Rahman II, RT.3/RW.10, Cibubur, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13720',
            //     'department_id'     => 'PLA',
            // ],
            // [
            //     'employee_name'     => 'Wahyudi Ribowo',
            //     'gender'            => 'Laki-Laki',
            //     'marital_status'    => 'Kawin',
            //     'num_children'      => 3,
            //     'image'             => 'default.png',
            //     'education'         => 'S1',
            //     'employee_address'  => 'Jl. Abdurrahman I No.181 A, RT.003/RW.010, Kel.Cibubur, Kec.Ciracas',
            //     'email'             => 'wahyudi@gmail.com',
            //     'telephone'         => '081281802255',
            //     'birth_place'       => 'Karanganyar',
            //     'birth_date'        => '1981-07-13',
            //     'hire_date'         => '2023-01-02',
            //     'contraceptive_use' => 'Tidak',
            //     'rptra_name'        => 'Cibubur Berseri',
            //     'rptra_address'     => 'Jl. H. Abdul Rahman II, RT.3/RW.10, Cibubur, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13720',
            //     'department_id'     => 'PLA',
            // ],
            // [
            //     'employee_name'     => 'Titik Juwita Sari',
            //     'gender'            => 'Perempuan',
            //     'marital_status'    => 'Kawin',
            //     'num_children'      => 3,
            //     'image'             => 'default.png',
            //     'education'         => 'SLTA',
            //     'employee_address'  => 'Jl. Taruna Jaya RT.013/RW.005, Kel.Cibubur, Kec.Ciracas',
            //     'email'             => 'titikjuwita19@gmail.com',
            //     'telephone'         => '0895371408908',
            //     'birth_place'       => 'Jakarta',
            //     'birth_date'        => '1980-09-19',
            //     'hire_date'         => '2023-01-02',
            //     'contraceptive_use' => 'Tidak',
            //     'rptra_name'        => 'Cibubur Berseri',
            //     'rptra_address'     => 'Jl. H. Abdul Rahman II, RT.3/RW.10, Cibubur, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13720',
            //     'department_id'     => 'PLA',
            // ],
            // [
            //     'employee_name'     => 'Rizka Rusthaliani',
            //     'gender'            => 'Perempuan',
            //     'marital_status'    => 'Kawin',
            //     'num_children'      => 0,
            //     'image'             => 'default.png',
            //     'education'         => 'S1',
            //     'employee_address'  => 'Jl. Lap. Tembak Gg.Damai No.33',
            //     'email'             => 'rizka77@gmail.com',
            //     'telephone'         => '089662036811',
            //     'birth_place'       => 'Jakarta',
            //     'birth_date'        => '1998-01-07',
            //     'hire_date'         => '2023-01-02',
            //     'contraceptive_use' => 'Tidak',
            //     'rptra_name'        => 'Cibubur Berseri',
            //     'rptra_address'     => 'Jl. H. Abdul Rahman II, RT.3/RW.10, Cibubur, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13720',
            //     'department_id'     => 'PLA',
            // ],
            // [
            //     'employee_name'     => 'Yuliardi',
            //     'gender'            => 'Laki-Laki',
            //     'marital_status'    => 'Kawin',
            //     'num_children'      => 2,
            //     'image'             => 'default.png',
            //     'education'         => 'SLTA',
            //     'employee_address'  => 'Jl. Cibubur III, RT.010/RW.001, Kel.Cibubur, Kec.Ciracas',
            //     'email'             => 'yuliardi99@gmail.com',
            //     'telephone'         => '081310710866',
            //     'birth_place'       => 'Jakarta',
            //     'birth_date'        => '1985-07-14',
            //     'hire_date'         => '2023-01-02',
            //     'contraceptive_use' => 'Tidak',
            //     'rptra_name'        => 'Cibubur Berseri',
            //     'rptra_address'     => 'Jl. H. Abdul Rahman II, RT.3/RW.10, Cibubur, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13720',
            //     'department_id'     => 'PLA',
            // ],
            [
                'employee_name'     => 'Admin Humaniora',
                'gender'            => 'Perempuan',
                'marital_status'    => 'Belum Kawin',
                'num_children'      => 0,
                'image'             => 'default.png',
                'education'         => 'S1 Teknik',
                'employee_address'  => 'Jl. Jakarta',
                'email'             => 'tamanhumaniora@gmail.com',
                'telephone'         => '081223344459',
                'birth_place'       => 'Jakarta',
                'birth_date'        => '1991-03-20',
                'hire_date'         => '2024-11-18',
                'contraceptive_use' => 'Tidak',
                'rptra_name'        => 'Taman Humaniora',
                'rptra_address'     => 'RT.2/RW.4, Rambutan, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13830',
                'department_id'     => 'ADM',
            ],
            [
                'employee_name'     => 'Admin Tanah Merdeka',
                'gender'            => 'Perempuan',
                'marital_status'    => 'Belum Kawin',
                'num_children'      => 0,
                'image'             => 'default.png',
                'education'         => 'S1 Teknik',
                'employee_address'  => 'Jl. Jakarta',
                'email'             => 'tanahmerdeka@gmail.com',
                'telephone'         => '081989998543',
                'birth_place'       => 'Jakarta',
                'birth_date'        => '1991-03-20',
                'hire_date'         => '2024-11-18',
                'contraceptive_use' => 'Tidak',
                'rptra_name'        => 'Tanah Merdeka',
                'rptra_address'     => 'Jl. Tanah Merdeka VII, RT.13/RW.6, Rambutan, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13830',
                'department_id'     => 'ADM',
            ],
            [
                'employee_name'     => 'Admin Jaya Makmur',
                'gender'            => 'Perempuan',
                'marital_status'    => 'Belum Kawin',
                'num_children'      => 0,
                'image'             => 'default.png',
                'education'         => 'S1 Teknik',
                'employee_address'  => 'Jl. Jakarta',
                'email'             => 'jayamakmur@gmail.com',
                'telephone'         => '081987654321',
                'birth_place'       => 'Jakarta',
                'birth_date'        => '1991-03-20',
                'hire_date'         => '2024-11-18',
                'contraceptive_use' => 'Tidak',
                'rptra_name'        => 'Jaya Makmur',
                'rptra_address'     => 'Jl. Jaya Makmur No.7 6, RT.6/RW.7, Klp. Dua Wetan, Kec. Ciracas, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13730',
                'department_id'     => 'ADM',
            ],
        ];

        // Insert batch data ke tabel employee
        $this->db->table('employee')->insertBatch($data);
    }
}
